### ISSUE TITLE
KvStoreClient.close() doesn't release all resources

### ISSUE THREAD

**Issue by andrewnet** [IBM/etcd-java#10]
I keep on doing the following, and the memory of the JVM quickly goes up and eventually crashed due to OOM. I know it is better to reuse the KvStoreClient instance, but closing it should release all the referenced memory.

1. Create KvStoreClient
2. Create a KV
3. Delete a KV
4. Close KvStoreClient

**Comment by andrewnet** [comment]
The memory leak seems to be some threads.
![image](https://user-images.githubusercontent.com/9754967/43284956-7a33a1e0-90eb-11e8-91ba-acfbd3f38f8f.png)

**Comment by njhill** [comment]
Thanks for reporting this @andrewnet, I have verified there is a problem and will have a fix soon.

**Comment by njhill** [comment]
@andrewnet I have a fix ready now https://github.com/IBM/etcd-java/pull/11. I will aim to include this in a new release within the next week.

As you mentioned, it's definitely much better to create a single client instance (per etcd cluster that you're talking to) and share/re-use it.
