### ISSUE TITLE
How to use prevExist and prevValue?

### ISSUE THREAD

**Issue by dasinihuiying** [IBM/etcd-java#14]
How to use prevExist and prevValue?

**Comment by njhill** [comment]
etcd-java is an etcd3 client, it sounds like you're asking about the etcd2 API.

You can perform the equivalent of `prevExist` and `prevValue` using etcd3 transactions, for example:

```java
PutRequest putReq = kvClient.put(key, newVal).asRequest();

// prevExist=false
kvClient.txnIf().notExists(key).then().put(putReq).sync();

// prevExist=true
kvClient.txnIf().exists(key).then().put(putReq).sync();

// prevValue
kvClient.txnIf().cmpEqual(key).value(oldVal).then().put(putReq).sync();
```

If you need to use an etcd2 server then you must use a different client.
