### ISSUE TITLE
Lease expiration managed by the PersistentLease?

### ISSUE THREAD

**Issue by hsyhsw** [IBM/etcd-java#23]
Hello! I'm facing some **spurious lease expiration** managed by the `PersistentLease` even if there're no network partition or hardware overloading issue.

The problem is that, sometimes, all leases managed by `PersistentLease`s get expired at the etcd server side and never go back active again (or re-granted) until the etcd server restarts. Actually a persistent lease instance is not notified of `LeaseState.EXPIRED` state even when a lease is actually expired at the etcd server when the issue hits. Interestingly, an `EXPIRED` event is fired immediately followed by an `ACTIVE` event fired when the client is reconnected to the restarted etcd server.

I believe (from some observation and code inspection) that the persistent lease monitors lease state and re-creates expired (not closed) lease and exposes its id through `PersistentLease.getLeaseID()` once a lease id renewed ~~so I send ttl request to assure the lease is OK to be related to an entity. (if ttl > 0 part)~~ Here's roughly what I'm doing to create/refresh a PersistentLease-tied entity.
```java
long getValidLease(PersistentLease lease) {
    validLease = -1;
    // lightly spin until I get a valid ttl response and id.
    // normally the body gets executed exactly once.
    do {
        // omitted: throw if the lease is CLOSED
        // since lease.getLeaseId() not guarantees a validness of the lease id,
        // I chose to use direct TTL request to query its state.
        ttlResp = etcdLease.ttl(lease.getLeaseId()); // lease id is updated by the event loop
        if (ttl > 0)
            validLease = ttlResp.getID();
    } while (lease.getCurrentTtlSecs() < 1); // also gets updated by the event loop
    return validLease;
}
long count(ByteString key) {
    return etcdKV.get(key).countOnly().async()
        .get(1000ms).getCount(); // 1 second timed wait-and-get
}

// operation PUT
long validLease = getValidLease(persistentLease);
etcdKV.put(key, data, validLease);

// operation REFRESH
if (count(key) == 0) {
    PUT_OPERATION(key, data); // put operation right above
}
```
All the entities (not many, < 20) get refreshed every 5 seconds. But after the **spurious lease expiration** all operations ~~hang at the do-while loop in the getValidLease~~ get expired lease ids through `getValidLease` and following operations fail because given lease id is already expired.

The etcd server looks OK: at that moment the etcd debug log shows that ~~TTL requests from the do-while loop arrive and get answered at very high rate (due to the do-while loop) and~~ further requests from clients (like etcdctl provided with the server distribution) get properly handled, and even granting a new lease from the same etcd-java client and making it persistent succeeds! It seems that the internal grpc client and event loop assigned with a persistent lease fail to handle responses from the server for some reason.

The issue appears randomly regardless of the server load status. As mentioned earlier, one simple solution for this is to restart the etcd server. After etcd-java reconnects to the restarted server and then all the operations work as expected again.

The etcd server (single instance configuration) is deployed in a small testbed and a spring boot application using etcd-java is also running at the same host, which means the client connects to the etcd server using `localhost` as the address.

Is there any recommended way dealing with the validness of a persistent lease, or am I missing something crucial?

**Comment by hsyhsw** [comment]
It turned out that the do-while loop issuing TTL request is redundant to get a valid lease id. Just watching for a lease state was enough.
However the problem itself still persists.

**Comment by njhill** [comment]
@hsyhsw thanks for the report. Could you provide a bit more information:
- What versions of etcd-java and etcd server are you using, what platform and java version?
- Could you give a more complete code example including how you create the client and `PersistentLease`?
- Do you have slf4j logging configured and if so are there any errors/stacktraces in the logs or stdout/err?
- Would you be able to provide a thread dump of the JVM when it's in this state (`kill -3`)

As you said in the followup, having a loop like this isn't a good idea and is unnecessary. If you want to create a lease and key tied to it at the same time you could do for example:
```java
// PersistentLease is also a Future which completes with the lease id once it's established
kvClient.put(key, data, lease.get()); 

// or async (failure handling omitted)
lease.addListener(() -> kvClient.put(key, data, lease.get()));
```
or best of all would be to use [`PersistentLeaseKey`](https://github.com/IBM/etcd-java/blob/master/src/main/java/com/ibm/etcd/client/utils/PersistentLeaseKey.java) if it fits your use case.

**Comment by hsyhsw** [comment]
Thanks for your support.
- I'm using the latest version of etcd-java (0.0.9) and etcd server (3.3.12) with 64-bit Java 8u181 all running under Windows 10
- slf4j is configured and there're some logs my app emitted catching exceptions thrown by etcd-java client, but I don't think they help... Below is the one logged when I tried creating a new entity with a lease id from an `ACTIVE` persistent lease.
```
io.grpc.StatusRuntimeException: NOT_FOUND: etcdserver: requested lease not found
    at io.grpc.Status.asRuntimeException(Status.java:521)
    at com.ibm.etcd.client.GrpcClient.waitFor(GrpcClient.java:650)
    at com.ibm.etcd.client.FluentRequest$AbstractFluentRequest.sync(FluentRequest.java:103)
        // tried putting entity because persistentlease-tied entity expired & deleted
    at my.app.Coordination.put(Coordination.java:1011)
        // RefreshEntity checks entity existence through calling etcdKV.get(key).countOnly().sync()
    at my.app.Coordination.$RefreshEntity.handle(Coordination.java:961)
    at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
    at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:57)
    at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
	...
```
Other than this, no error or error-indicating logs were found.

Currently, I'm doing the following to create an entity. It is quite plain code suggested in the README file.
```java
EtcdClient etcd = EtcdClient.forEndpoints("localhost:port").withPlainText().build();
LeaseClient etcdLease = etcd.getLeaseClient();
KvClient etcdKV = etcd.getKvClient();

// this is slightly different from the session lease in its lifecycle, anyway, it's just a persistent lease
PersistentLease sharedLease = etcdLease.maintain().start(loggingObserver);
// omitted: sharedLease.get() to ensure the persistent lease established

void put(ByteString key, ByteString value) {
    long newLease = etcdLease.grant(DEFAULT_TTL).sync().getID();
    if (sharedLease.getState() == LeaseState.ACTIVE) {
        // this always fails once the incident occurs with an exception
        // io.grpc.StatusRuntimeException: NOT_FOUND: etcdserver: requested lease not found
        etcdKV.put(key, value, sharedLease.getLeaseId()).sync();
    } else {
        // throw
    }
}
```

I think it is problematic the state of a persistent lease not properly getting updated once the incident occurs.
I considered adopting `PersistentLeaseKey` you've suggested, regretably, it slightly not fits my usecase.

Here's the thread dump for the etcd related threads. Would this be enough?
```
"etcd-callback-thread-25" #463 daemon prio=5 os_prio=0 tid=0x0000000019578000 nid=0x51bc waiting on condition [0x00000000470ee000]
   java.lang.Thread.State: TIMED_WAITING (parking)
        at sun.misc.Unsafe.park(Native Method)
        - parking to wait for  <0x0000000081797500> (a java.util.concurrent.SynchronousQueue$TransferStack)
        at java.util.concurrent.locks.LockSupport.parkNanos(Unknown Source)
        at java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(Unknown Source)
        at java.util.concurrent.SynchronousQueue$TransferStack.transfer(Unknown Source)
        at java.util.concurrent.SynchronousQueue.poll(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)

   Locked ownable synchronizers:
        - None

"etcd-event-pool-3" #30 daemon prio=5 os_prio=0 tid=0x00000000224e0800 nid=0x5e74 runnable [0x0000000023c7e000]
   java.lang.Thread.State: RUNNABLE
        at sun.nio.ch.WindowsSelectorImpl$SubSelector.poll0(Native Method)
        at sun.nio.ch.WindowsSelectorImpl$SubSelector.poll(Unknown Source)
        at sun.nio.ch.WindowsSelectorImpl$SubSelector.access$400(Unknown Source)
        at sun.nio.ch.WindowsSelectorImpl.doSelect(Unknown Source)
        at sun.nio.ch.SelectorImpl.lockAndDoSelect(Unknown Source)
        - locked <0x00000000817ff668> (a io.netty.channel.nio.SelectedSelectionKeySet)
        - locked <0x0000000081918800> (a java.util.Collections$UnmodifiableSet)
        - locked <0x00000000817ff598> (a sun.nio.ch.WindowsSelectorImpl)
        at sun.nio.ch.SelectorImpl.select(Unknown Source)
        at io.netty.channel.nio.SelectedSelectionKeySetSelector.select(SelectedSelectionKeySetSelector.java:62)
        at io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:765)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:413)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:909)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Unknown Source)

   Locked ownable synchronizers:
        - None

"etcd-event-pool-2" #29 daemon prio=5 os_prio=0 tid=0x000000001a55c000 nid=0x56b8 runnable [0x000000002377f000]
   java.lang.Thread.State: RUNNABLE
        at sun.nio.ch.WindowsSelectorImpl$SubSelector.poll0(Native Method)
        at sun.nio.ch.WindowsSelectorImpl$SubSelector.poll(Unknown Source)
        at sun.nio.ch.WindowsSelectorImpl$SubSelector.access$400(Unknown Source)
        at sun.nio.ch.WindowsSelectorImpl.doSelect(Unknown Source)
        at sun.nio.ch.SelectorImpl.lockAndDoSelect(Unknown Source)
        - locked <0x000000008196eae0> (a io.netty.channel.nio.SelectedSelectionKeySet)
        - locked <0x000000008196ec18> (a java.util.Collections$UnmodifiableSet)
        - locked <0x000000008196eaf8> (a sun.nio.ch.WindowsSelectorImpl)
        at sun.nio.ch.SelectorImpl.select(Unknown Source)
        at io.netty.channel.nio.SelectedSelectionKeySetSelector.select(SelectedSelectionKeySetSelector.java:62)
        at io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:765)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:413)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:909)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Unknown Source)

   Locked ownable synchronizers:
        - None

"etcd-event-pool-1" #27 daemon prio=5 os_prio=0 tid=0x000000001a742000 nid=0x4d94 runnable [0x000000002357e000]
   java.lang.Thread.State: RUNNABLE
        at sun.nio.ch.WindowsSelectorImpl$SubSelector.poll0(Native Method)
        at sun.nio.ch.WindowsSelectorImpl$SubSelector.poll(Unknown Source)
        at sun.nio.ch.WindowsSelectorImpl$SubSelector.access$400(Unknown Source)
        at sun.nio.ch.WindowsSelectorImpl.doSelect(Unknown Source)
        at sun.nio.ch.SelectorImpl.lockAndDoSelect(Unknown Source)
        - locked <0x0000000081827d50> (a io.netty.channel.nio.SelectedSelectionKeySet)
        - locked <0x0000000081827da8> (a java.util.Collections$UnmodifiableSet)
        - locked <0x0000000081827c80> (a sun.nio.ch.WindowsSelectorImpl)
        at sun.nio.ch.SelectorImpl.select(Unknown Source)
        at io.netty.channel.nio.SelectedSelectionKeySetSelector.select(SelectedSelectionKeySetSelector.java:62)
        at io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:765)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:413)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:909)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Unknown Source)

   Locked ownable synchronizers:
        - None

"etcd-event-pool-0" #26 daemon prio=5 os_prio=0 tid=0x0000000018d16800 nid=0x43b0 runnable [0x000000002220e000]
   java.lang.Thread.State: RUNNABLE
        at sun.nio.ch.WindowsSelectorImpl$SubSelector.poll0(Native Method)
        at sun.nio.ch.WindowsSelectorImpl$SubSelector.poll(Unknown Source)
        at sun.nio.ch.WindowsSelectorImpl$SubSelector.access$400(Unknown Source)
        at sun.nio.ch.WindowsSelectorImpl.doSelect(Unknown Source)
        at sun.nio.ch.SelectorImpl.lockAndDoSelect(Unknown Source)
        - locked <0x00000000818b2c40> (a io.netty.channel.nio.SelectedSelectionKeySet)
        - locked <0x00000000818b2d78> (a java.util.Collections$UnmodifiableSet)
        - locked <0x00000000818b2c58> (a sun.nio.ch.WindowsSelectorImpl)
        at sun.nio.ch.SelectorImpl.select(Unknown Source)
        at io.netty.channel.nio.SelectedSelectionKeySetSelector.select(SelectedSelectionKeySetSelector.java:62)
        at io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:765)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:413)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:909)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Unknown Source)

   Locked ownable synchronizers:
        - None
```

It is unclear how to reproduce it exactly but it happens eventually waiting after creating some persistent leases and entities.

**Comment by njhill** [comment]
Thanks a lot @hsyhsw for that detail. Do you log all exceptions caught (just want to make sure there aren't any happening which are being hidden)? I know the problem is intermittent but I wonder if you could provide a self-contained reproducer which exhibits the problem after some time, which I could use to try and reproduce on my end?

Also if it's possible to share, I'd be interested to know how your use-case differs from what's provided by `PersistentLeaseKey`.

**Comment by hsyhsw** [comment]
OK. I'll post an executable jar along with all source files when it is available. It may take some time to test whether it is the right reproducer.

**Comment by njhill** [comment]
Thanks @hsyhsw, no need to include a jar, just (preferably minimal) source code, e.g. just a class with main method would be great.

**Comment by hsyhsw** [comment]
@njhill This code reproduces the issue. The observers may be omitted, however not verified to reproduce without it. Just make it running for a few days. Usually takes a day or two though.
```java
public class App {

	static final ByteString ENTITY_VALUE = ByteString.copyFromUtf8("some_value");
	static final Logger log = LoggerFactory.getLogger(App.class);

	static final int PORT = 18022;
	static EtcdClient etcd = EtcdClient.forEndpoint("localhost", PORT).withPlainText().build();
	static KvClient etcdKV = etcd.getKvClient();
	static LeaseClient etcdLease = etcd.getLeaseClient();

	static Map<String, PersistentLease> leaseMap = new HashMap<>();

	public static void main(String[] args) throws Exception {
		// put 5 entities
		for (int i = 0; i < 5; ++i) {
			String key = "some_key_" + i;
			long leaseId = etcdLease.grant(20L).sync().getID();
			etcdKV.put(ByteString.copyFromUtf8(key), ENTITY_VALUE, leaseId).sync();
			PersistentLease newLease = etcdLease.maintain().leaseId(leaseId).start(new LeaseObserver(key));
			leaseMap.put(key, newLease);
		}

		etcdKV.watch(ByteString.copyFromUtf8("some_watch_key_")).asPrefix().start(new StreamObserver<WatchUpdate>() {

			@Override
			public void onNext(WatchUpdate value) {
				log.info("Watch onNext: " + value);
			}

			@Override
			public void onError(Throwable t) {
				log.info("Watch onError", t);
			}

			@Override
			public void onCompleted() {
				log.info("Watch onCompleted");
			}
		});

		// periodic refresh
		ScheduledExecutorService refreshLoop = Executors.newSingleThreadScheduledExecutor();
		refreshLoop.scheduleAtFixedRate(App::refresh, 5L, 5L, TimeUnit.SECONDS);
		
		while (true) {
			// this works well even after that happens
			long leaseId = etcdLease.grant(20L).sync().getID();
			etcdKV.put(ByteString.copyFromUtf8("transient_key"), ENTITY_VALUE, leaseId).sync();
			PersistentLease newLease = etcdLease.maintain().leaseId(leaseId).start(new LeaseObserver("transient_key"));
			newLease.get();
			Thread.sleep(3000);
			newLease.close();
			Thread.sleep(3000);
		}
	}

	static void refresh() {
		for (Entry<String, PersistentLease> ent : leaseMap.entrySet()) {
			try {
				ByteString key = ByteString.copyFromUtf8(ent.getKey());
				if (etcdKV.get(key).countOnly().sync().getCount() == 0) { // deleted
					log.warn("Expired, reputting: " + ent.getKey());
					if (ent.getValue().getState() == LeaseState.ACTIVE) {
						etcdKV.put(key, ENTITY_VALUE, ent.getValue().getLeaseId()).async().get(800L, TimeUnit.MILLISECONDS);
					}
				}
			} catch (Exception e) {
				log.error("Failed: " + ent.getKey(), e);
			}
		}
	}
}

class LeaseObserver implements StreamObserver<LeaseState> {

	static Logger log = LoggerFactory.getLogger(LeaseObserver.class);

	private LeaseState lastState;

	private String key;

	public LeaseObserver(String key) {
		this.lastState = LeaseState.PENDING;
		this.key = key;
		log.info(String.format("Persistent lease observer initialized for entity %s", key));
	}

	@Override
	public void onCompleted() {
		log.info(String.format("Persistent lease revoked: %s", key));
	}

	@Override
	public void onError(Throwable err) {
		log.error(String.format("Persistent lease error: %s", key), err);
	}

	@Override
	public void onNext(LeaseState state) {
		log.info(String.format("Persistent lease state changed: %s (%s -> %s)", key, lastState, state));
		lastState = state;
	}
}

**Comment by njhill** [comment]
Thanks a lot @hsyhsw and sorry for the delay I was on vac last week. I will play with it this week and try to get to the bottom of it.

**Comment by njhill** [comment]
@hsyhsw unfortunately I haven't yet managed to repro myself (have not run your code for more than about a day yet though). It's also not something I've observed in our own extensive production usage, but that could just be due to your usage pattern being different.

Symptom-wise it appears like the lease keepalive stream becomes "broken" in some way, which could either be that we are no longer sending reqs through it or sending them and no responses are coming back. The leases/keys you create in the subsequent loop _would_ use this same stream but they are closed prior to keepalives being needed, so it doesn't necessarily provide any clue about the stream's health at this point. It's likely still considered connected, otherwise there would be a failure event and it would reconnect / establish the stream (as you observe when restarting the server in this state). So I may resort to more detailed static analysis to narrow in on what kind of conditions could cause it to end up in such a state.

Probably not directly related to the issue but re your example there's a cleaner way of creating a lease + key pair. Instead of:
```java
long leaseId = etcdLease.grant(20L).sync().getID();
etcdKV.put(ByteString.copyFromUtf8("transient_key"), ENTITY_VALUE, leaseId).sync();
PersistentLease newLease = etcdLease.maintain().leaseId(leaseId).start(new LeaseObserver("transient_key"));
```
it would be better to do:
```java
PersistentLease newLease = etcdLease.maintain().start(new LeaseObserver("transient_key"));
Futures.transformAsync(newLease, leaseId -> etcdKV.put(
    ByteString.copyFromUtf8("transient_key"), ENTITY_VALUE, leaseId).async(), Runnable::run).get();
```
i.e. you should rarely need to use `grant()` explicitly. Also still curious how your use-case differs from what's provided by `PersistentLeaseKey` if you are able to share that :)

FYI I am planning to release a new version, mainly with dependency updates. I'd like to find/fix this first of but if I'm unable to soon then I will likely release it regardless.

Thanks again for helping with this.

**Comment by hsyhsw** [comment]
@njhill Thanks for your effort.
The while loop repeatedly granting and closing the lease was just to accelerate(?) a reproduction. It is reproducible without it.
I think the `PersistentLeaseKey` is not applicable since putting an key-value entity involves some transactions, not simply maintaining a lease-kv relationship. (also, it is reproducible without transactions)
I applied your suggestion from the code snippet. Thnaks!

Currently I'm just periodically checking the lease states and re-granting if needed as a workaround. This is working fine for now but should be resolved anyway... Hopefully, in the next release the issue would be investigated and fixed. Thanks again for your effort!

**Comment by njhill** [comment]
@hsyhsw it seems unlikely that this would resolve your issue but now that v0.0.10 is released I wonder if you could upgrade and verify whether it still happens?

**Comment by hsyhsw** [comment]
@njhill yeap. I could test with the upgraded lib and will let you know.
It may take some time cuz I have vac plan on the next week. Hayppy May Day!

**Comment by hsyhsw** [comment]
So far so good! The reproducer is running for about 5 days with no issue! Surprisingly, it seems that the updates on grpc, netty are working somehow! :)

I'm leaving for vacation tomorrow, till next Monday. I'm gonna update the status again next Tuesday.

**Comment by njhill** [comment]
@hsyhsw great! Thanks again and fingers crossed...

**Comment by hsyhsw** [comment]
@njhill The code above still not reveals the issue. No leases get expired spuriously so far. Great thanks for your help.
Would it be safe to assume this issue closed for now?

**Comment by njhill** [comment]
Thanks @hsyhsw, let me know if you run into any similar issues in future!

**Comment by hsyhsw** [comment]
The same issue persists. I think the last time was a great luck....

**Comment by njhill** [comment]
@hsyhsw :( thanks for letting me know, I will have to dig in more and try to flush this out when I get a chance.

**Comment by njhill** [comment]
@hsyhsw I've released a new version `0.0.11` which includes some lease-resiliency related improvements. They primarily apply to the use of `PersistentLeaseKey` but there are also some changes to `PersistentLease` so I have some hope that it may resolve the issue you saw, that is if you are still using etcd-java!

**Comment by hsyhsw** [comment]
Running all OK from the 0.0.11 release on the local testbed.

Sorry to say that I'm no longer a main developer for the project where the OPs issue was found as I've been assigned to another project long ago. Anyway, I'm gonna notice the dev guy working on the project to apply it and keep you posted for the further issue if any.
Thanks for your help!

**Comment by njhill** [comment]
Great, thanks @hsyhsw! (though I know it took a long time to show up last time you tried so maybe it's not definite yet...)
