### ISSUE TITLE
Is some source missing ?

### ISSUE THREAD

**Issue by mgfairfax** [IBM/etcd-java#3]
some of the imports are from the package com.ibm.etcd.api which does not seem to be there; for example from KVClient.java 
imports like these below

import com.ibm.etcd.api.PutRequest;
import com.ibm.etcd.api.PutRequestOrBuilder;
import com.ibm.etcd.api.PutResponse;
import com.ibm.etcd.api.RangeRequest;
...

**Comment by njhill** [comment]
@mgfairfax these are classes corresponding to the protocol buffer message types used in etcd's gRPC 
 interface. They are "compiled" from the `.proto` file definitions (in /src/main/proto) into java source files. This can be done using the `protoc` tool directly or automatically when building via a maven plugin.

You should see that these get generated when building the client using `mvn install`.

**Comment by mgfairfax** [comment]
thank you! Didnt realize these are generated classes.
