### ISSUE TITLE
 In EtcdClient.forEndpoints(xxx).withSessionTimeoutSecs(); Why is the verification completely opposite after version 0.015;

### ISSUE THREAD

**Issue by dpzain** [IBM/etcd-java#45]
0.0.14 version:
```java
         if (timeoutSecs < 1) {
                throw new IllegalArgumentException("invalid session timeout: " + timeoutSecs);
            }
```
after 0.0.15 version:
```java
          Preconditions.checkArgument(timeoutSecs < 1, "invalid session timeout: %s", timeoutSecs);
```
   guava:
```java
      public static void checkArgument(boolean b, @Nullable String errorMessageTemplate, int p1) {
        if (!b) { //The time before was always 5   this is true!!!!!!!!!!!!!!
            throw new IllegalArgumentException(Strings.lenientFormat(errorMessageTemplate, new Object[]{p1}));
        }
    }
```

**Comment by dpzain** [comment]
` public Builder withSessionTimeoutSecs(int timeoutSecs) {
            if (timeoutSecs < 1) {
                throw new IllegalArgumentException("invalid session timeout: " + timeoutSecs);
            }
            this.sessTimeoutSecs = timeoutSecs;
            return this;
        }`

`public Builder withSessionTimeoutSecs(int timeoutSecs) {
            Preconditions.checkArgument(timeoutSecs < 1, "invalid session timeout: %s", timeoutSecs);
            this.sessTimeoutSecs = timeoutSecs;
            return this;
        }`
` public static void checkArgument(boolean b, @Nullable String errorMessageTemplate, int p1) {
        if (!b) {
            throw new IllegalArgumentException(Strings.lenientFormat(errorMessageTemplate, new Object[]{p1}));
        }
    }`

**Comment by dpzain** [comment]
`java
public Builder withSessionTimeoutSecs(int timeoutSecs) { if (timeoutSecs < 1) { throw new IllegalArgumentException("invalid session timeout: " + timeoutSecs); } this.sessTimeoutSecs = timeoutSecs; return this; }
`

**Comment by njhill** [comment]
Thanks @dpzain this is obviously a bug. I'll ensure that it's fixed in the next release.

**Comment by dpzain** [comment]
> Thanks @dpzain this is obviously a bug. I'll ensure that it's fixed in the next release.

ok !

**Comment by sherman** [comment]
Hi, @njhill!
Do you have plans to release the fix?

**Comment by njhill** [comment]
@sherman sure I will aim to do a new release soon. I'd ideally like to address #49 too.

You are probably aware of this but there is a default session timeout of 20 secs, this bug just prevents that being overridden.
