### ISSUE TITLE
Issue with protobuf-maven-plugin

### ISSUE THREAD

**Issue by punith-nb** [IBM/etcd-java#55]
I am getting the below error 👍 
```
 Failed to execute goal org.xolstice.maven.plugins:protobuf-maven-plugin:0.6.1:compile-custom (default) on project etcd-java: Unable to resolve artifact: Missing:
[ERROR] ----------
[ERROR] 1) io.grpc:protoc-gen-grpc-java:exe:linux-ppcle_64:1.36.1
[ERROR]
[ERROR]   Try downloading the file manually from the project website.
[ERROR]
[ERROR]   Then, install it using the command:
[ERROR]       mvn install:install-file -DgroupId=io.grpc -DartifactId=protoc-gen-grpc-java -Dversion=1.36.1 -Dclassifier=linux-ppcle_64 -Dpackaging=exe -Dfile=/path/to/file
[ERROR]
[ERROR]   Alternatively, if you host your own repository you can deploy the file there:
[ERROR]       mvn deploy:deploy-file -DgroupId=io.grpc -DartifactId=protoc-gen-grpc-java -Dversion=1.36.1 -Dclassifier=linux-ppcle_64 -Dpackaging=exe -Dfile=/path/to/file -Durl=[url] -DrepositoryId=[id]
[ERROR]
[ERROR]   Path to dependency:
[ERROR]         1) com.ibm.etcd:etcd-java:jar:0.0.19-SNAPSHOT
[ERROR]         2) io.grpc:protoc-gen-grpc-java:exe:linux-ppcle_64:1.36.1
[ERROR]
[ERROR] ----------
[ERROR] 1 required artifact is missing.
[ERROR]
[ERROR] for artifact:
[ERROR]   com.ibm.etcd:etcd-java:jar:0.0.19-SNAPSHOT
[ERROR]
[ERROR] from the specified remote repositories:
[ERROR]   central (https://repo.maven.apache.org/maven2, releases=true, snapshots=false)
[ERROR]
```

**Comment by punith-nb** [comment]
I am getting this issue on ppc64le architecture.

**Comment by punith-nb** [comment]
The above issue got resolved..

**Comment by punith-nb** [comment]
I am getting the below error while running test.
I am running **mvn test** 

[INFO] Running com.ibm.etcd.client.EtcdTestSuite
Failed to start etcd: java.io.IOException: Cannot run program "etcd": error=2, No such file or directory
Failed to start etcd: java.io.IOException: Cannot run program "etcd": error=2, No such file or directory
Failed to start etcd: java.io.IOException: Cannot run program "etcd": error=2, No such file or directory
localproxy about to start on port 2391
localproxy started on port 2391 in 8ms
localproxy on port 2391 about to forcibly stop
localproxy on port 2391 stopped in 1ms
localproxy about to start on port 2390
localproxy started on port 2390 in 0ms
[etcd-event-pool-4] INFO com.ibm.etcd.client.GrpcClient - Retryable onError #1 on underlying stream of method etcdserverpb.Watch/Watch: io.grpc.StatusRuntimeException: UNAVAILABLE: Network closed for unknown reason
[etcd-event-pool-4] INFO com.ibm.etcd.client.GrpcClient - Retryable onError #2 on underlying stream of method etcdserverpb.Watch/Watch: io.grpc.StatusRuntimeException: UNAVAILABLE: Network closed for unknown reason
[etcd-event-pool-0] INFO com.ibm.etcd.client.GrpcClient - Retryable onError #3 on underlying stream of method etcdserverpb.Watch/Watch: io.grpc.StatusRuntimeException: UNAVAILABLE: Network closed for unknown reason
localproxy on port 2390 about to forcibly stop
localproxy on port 2390 stopped in 0ms
1.015 watch completed
[etcd-event-pool-5] INFO com.ibm.etcd.client.GrpcClient - Retryable onError #1 on underlying stream of method etcdserverpb.Watch/Watch: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
[etcd-event-pool-5] INFO com.ibm.etcd.client.GrpcClient - Retryable onError #2 on underlying stream of method etcdserverpb.Watch/Watch: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
[etcd-event-pool-1] INFO com.ibm.etcd.client.GrpcClient - Retryable onError #3 on underlying stream of method etcdserverpb.Watch/Watch: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
[etcd-event-pool-5] INFO com.ibm.etcd.client.GrpcClient - Retryable onError #4 on underlying stream of method etcdserverpb.Watch/Watch: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
[etcd-event-pool-5] INFO com.ibm.etcd.client.GrpcClient - Retryable onError #5 on underlying stream of method etcdserverpb.Watch/Watch: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
[etcd-event-pool-3] INFO com.ibm.etcd.client.GrpcClient - Retryable onError #6 on underlying stream of method etcdserverpb.Watch/Watch: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
[etcd-event-pool-1] INFO com.ibm.etcd.client.GrpcClient - Retryable onError #7 on underlying stream of method etcdserverpb.Watch/Watch: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
[etcd-event-pool-5] INFO com.ibm.etcd.client.GrpcClient - Retryable onError #8 on underlying stream of method etcdserverpb.Watch/Watch: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
[etcd-event-pool-1] INFO com.ibm.etcd.client.GrpcClient - Retryable onError #9 on underlying stream of method etcdserverpb.Watch/Watch: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
[etcd-event-pool-5] INFO com.ibm.etcd.client.GrpcClient - Retryable onError #10 on underlying stream of method etcdserverpb.Watch/Watch: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception

**Comment by punith-nb** [comment]
Is there any specific way for testing?

**Comment by njhill** [comment]
@punith-nb the unit tests require a local running etcd server listening on port 2379. This is very easy to start - just follow the examples in the [etcd release notes](https://github.com/etcd-io/etcd/releases)
```
# start a local etcd server
/tmp/etcd-download-test/etcd
```
It's done by [this script](https://github.com/IBM/etcd-java/blob/main/build-env/install-etcd.sh) in the CI.

**Comment by njhill** [comment]
@punith-nb I'm going to close this now but feel free to re-open if you have more questions.
