### ISSUE TITLE
not found class com.ibm.etcd.api.AuthGrpc and KVGrpc

### ISSUE THREAD

**Issue by Shadow-Java** [IBM/etcd-java#67]
hello,i build this project but it suggests me 'java:no found calss com.ibm.etcd.api.AuthGrpc & com.ibm.etcd.api.KVGrpc';
can you tell me how to deal with this error?

**Comment by njhill** [comment]
@Shadow-Java these are grpc/protobuf stubs which are generated by the proto compiler as part of the build, prior to other compilation.

You should be able to build everything by just running `mvn install`, or to just generate those .java stubs `mvn generate-sources`.

**Comment by njhill** [comment]
@Shadow-Java please reopen if you still have a problem, thanks.
